format_version: 10
pipelines:
  frontend:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-2b6f81a:
        git: https://github.com/chaitus09/ansible_repo.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - ansible-playbook:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            ansible-playbook:
              timeout: 0
              tasks:
                  - exec:
                    arguments:
                      - ansible.sh
                      - frontend
                    command: bash
                    run_if: passed
